from django.urls import path
from django.urls.resolvers import URLPattern
from .views import *

urlpatterns = [
    path('', Home),
    path('api/all-newlist/',all_newlist),
    path('api/login/',login),
    path('api/register/',register),
    path('api/post-newlist/',post_newlist),
    path('api/update-newlist/<int:TID>', update_newlist),
    path('api/delete-newlist/<int:TID>', delete_newlist),
    path('api/all-devicelist1/',all_devicelist1),
    path('api/post-devicelist1/',post_devicelist1),
    path('api/update-devicelist1/<int:TID>', update_devicelist1),
    path('api/delete-devicelist1/<int:TID>', delete_devicelist1),
    path('api/all-devicelist2/',all_devicelist2),
    path('api/post-devicelist2/',post_devicelist2),
    path('api/update-devicelist2/<int:TID>', update_devicelist2),
    path('api/delete-devicelist2/<int:TID>', delete_devicelist2),
    path('api/all-devicelist3/',all_devicelist3),
    path('api/post-devicelist3/',post_devicelist3),
    path('api/update-devicelist3/<int:TID>', update_devicelist3),
    path('api/delete-devicelist3/<int:TID>', delete_devicelist3),
    # path('api/all-name1/',all_name1),
    # path('api/post-name1/',post_name1),
    # path('api/update-name1/<int:TID>', update_name1),
    # path('api/all-name2/',all_name2),
    # path('api/post-name2/',post_name2),
    # path('api/update-name2/<int:TID>', update_name2),
    # path('api/all-name3/',all_name3),
    # path('api/post-name3/',post_name3),
    # path('api/update-name3/<int:TID>', update_name3),
    # path('api/all-name4/',all_name4),
    # path('api/post-name4/',post_name4),
    # path('api/update-name4/<int:TID>', update_name4),
    # path('api/all-name5/',all_name5),
    # path('api/post-name5/',post_name5),
    # path('api/update-name5/<int:TID>', update_name5),
    # path('api/all-name6/',all_name6),
    # path('api/post-name6/',post_name6),
    # path('api/update-name6/<int:TID>', update_name6),

]
