# Generated by Django 3.2 on 2022-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='qrname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
