# Generated by Django 3.2 on 2022-02-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_alter_device_qrname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='qrname',
            new_name='qrname1',
        ),
        migrations.AddField(
            model_name='device',
            name='qrname2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='qrname3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
