# Generated by Django 3.2 on 2022-02-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_auto_20220208_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrname1', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrname2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrname3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
