# Generated by Django 3.2 on 2022-02-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0005_name1_name2_name3_name4_name5_name6'),
    ]

    operations = [
        migrations.AddField(
            model_name='device1',
            name='namesw1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device2',
            name='namesw21',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device2',
            name='namesw22',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device3',
            name='namesw31',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device3',
            name='namesw32',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device3',
            name='namesw33',
            field=models.TextField(blank=True, null=True),
        ),
    ]
