# Generated by Django 3.2 on 2022-03-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0008_auto_20220303_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name1',
        ),
        migrations.DeleteModel(
            name='name2',
        ),
        migrations.DeleteModel(
            name='name3',
        ),
        migrations.DeleteModel(
            name='name4',
        ),
        migrations.DeleteModel(
            name='name5',
        ),
        migrations.DeleteModel(
            name='name6',
        ),
    ]
